# Generated by Django 4.2.7 on 2025-11-03 02:24

from django.db import migrations


def create_defaults(apps, schema_editor):
    Location = apps.get_model("dashboard", "Location")
    defaults = [
        {"slug": "trans", "name": "TRANS", "order": 0},
        {"slug": "p1", "name": "P1", "order": 1},
        {"slug": "p2", "name": "P2", "order": 2},
        {"slug": "p3", "name": "P3", "order": 3},
        {"slug": "p4", "name": "P4", "order": 4},
    ]
    for data in defaults:
        Location.objects.get_or_create(slug=data["slug"], defaults=data)


def remove_defaults(apps, schema_editor):
    Location = apps.get_model("dashboard", "Location")
    Location.objects.filter(slug__in=["trans", "p1", "p2", "p3", "p4"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_defaults, remove_defaults)]
