# Generated by Django 4.2.7 on 2025-11-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_seed_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationmessage",
            name="is_important",
            field=models.BooleanField(default=False),
        ),
    ]
