# Generated by Django 4.2.7 on 2025-11-12 05:41

from django.db import migrations


def create_strefy(apps, schema_editor):
    Location = apps.get_model("dashboard", "Location")
    Location.objects.get_or_create(
        slug="strefy",
        defaults={"name": "STREFY", "order": 5},
    )


def remove_strefy(apps, schema_editor):
    Location = apps.get_model("dashboard", "Location")
    Location.objects.filter(slug="strefy").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_locationmessage_is_important"),
    ]

    operations = [
        migrations.RunPython(create_strefy, remove_strefy),
    ]
