# Generated by Django 4.2.7 on 2025-11-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_add_strefy_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThemeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board_bg_top", models.CharField(default="#03102a", max_length=20)),
                ("board_bg_bottom", models.CharField(default="#021a32", max_length=20)),
                (
                    "board_panel",
                    models.CharField(default="rgba(10, 23, 41, 0.78)", max_length=30),
                ),
                ("board_text_main", models.CharField(default="#f4fff6", max_length=20)),
                (
                    "board_text_muted",
                    models.CharField(default="#8ba0bf", max_length=20),
                ),
                ("board_accent", models.CharField(default="#54f6a2", max_length=20)),
                ("board_important", models.CharField(default="#ff4b55", max_length=20)),
                (
                    "board_green_layer_start",
                    models.CharField(default="#0c3a27", max_length=20),
                ),
                (
                    "board_green_layer_end",
                    models.CharField(default="#0f5f3d", max_length=20),
                ),
                (
                    "board_green_inner_start",
                    models.CharField(default="rgba(18, 69, 46, 0.95)", max_length=30),
                ),
                (
                    "board_green_inner_end",
                    models.CharField(default="rgba(8, 43, 29, 0.98)", max_length=30),
                ),
                (
                    "board_blue_layer_start",
                    models.CharField(default="#0b1f52", max_length=20),
                ),
                (
                    "board_blue_layer_end",
                    models.CharField(default="#123c84", max_length=20),
                ),
                (
                    "board_blue_inner_start",
                    models.CharField(default="rgba(16, 47, 104, 0.92)", max_length=30),
                ),
                (
                    "board_blue_inner_end",
                    models.CharField(default="rgba(9, 31, 74, 0.96)", max_length=30),
                ),
                (
                    "board_red_layer_start",
                    models.CharField(default="#61121a", max_length=20),
                ),
                (
                    "board_red_layer_end",
                    models.CharField(default="#b12332", max_length=20),
                ),
                (
                    "board_red_inner_start",
                    models.CharField(default="rgba(144, 26, 36, 0.95)", max_length=30),
                ),
                (
                    "board_red_inner_end",
                    models.CharField(default="rgba(82, 12, 18, 0.98)", max_length=30),
                ),
                ("leader_bg_top", models.CharField(default="#03102a", max_length=20)),
                (
                    "leader_bg_bottom",
                    models.CharField(default="#021a32", max_length=20),
                ),
                (
                    "leader_panel",
                    models.CharField(default="rgba(10, 23, 41, 0.78)", max_length=30),
                ),
                (
                    "leader_text_main",
                    models.CharField(default="#f4fff6", max_length=20),
                ),
                (
                    "leader_border",
                    models.CharField(
                        default="rgba(255, 255, 255, 0.18)", max_length=20
                    ),
                ),
                (
                    "leader_card",
                    models.CharField(default="rgba(5, 17, 32, 0.7)", max_length=30),
                ),
                (
                    "leader_message_card",
                    models.CharField(default="rgba(11, 29, 51, 0.75)", max_length=30),
                ),
                (
                    "leader_input_bg",
                    models.CharField(default="rgba(3, 14, 28, 0.8)", max_length=30),
                ),
                (
                    "leader_input_border",
                    models.CharField(
                        default="rgba(255, 255, 255, 0.25)", max_length=30
                    ),
                ),
                (
                    "leader_button_from",
                    models.CharField(default="#1b8f64", max_length=20),
                ),
                (
                    "leader_button_to",
                    models.CharField(default="#2fd48c", max_length=20),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Theme settings",
            },
        ),
    ]
