# Generated by Django 4.2.7 on 2025-11-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_themesettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="themesettings",
            name="leader_border",
            field=models.CharField(default="rgba(255, 255, 255, 0.18)", max_length=40),
        ),
        migrations.AlterField(
            model_name="themesettings",
            name="leader_card",
            field=models.CharField(default="rgba(5, 17, 32, 0.7)", max_length=40),
        ),
        migrations.AlterField(
            model_name="themesettings",
            name="leader_input_bg",
            field=models.CharField(default="rgba(3, 14, 28, 0.8)", max_length=40),
        ),
        migrations.AlterField(
            model_name="themesettings",
            name="leader_input_border",
            field=models.CharField(default="rgba(255, 255, 255, 0.25)", max_length=40),
        ),
        migrations.AlterField(
            model_name="themesettings",
            name="leader_message_card",
            field=models.CharField(default="rgba(11, 29, 51, 0.75)", max_length=40),
        ),
        migrations.AlterField(
            model_name="themesettings",
            name="leader_panel",
            field=models.CharField(default="rgba(10, 23, 41, 0.78)", max_length=40),
        ),
    ]
